### ISSUE TITLE
麦子scatter 钱包 使用scatter.authenticate认证方法 返回空字符串

### ISSUE THREAD

**Issue by qinxiaowen** [MediShares/scatter-eos-sample#2]

**Comment by qinxiaowen** [comment]
![image](https://user-images.githubusercontent.com/8536046/57985648-9fbe1700-7a9d-11e9-92e4-b77385522d85.png)
控制台输出3333
https://get-scatter.com/docs/api-authenticate
![image](https://user-images.githubusercontent.com/8536046/57985659-d1cf7900-7a9d-11e9-9200-164a9d62f5b9.png)

**Comment by yuzhiyou1990** [comment]
麦子钱包手机端，暂不支持 scatter.authenticate。
